dist: trusty
sudo: false
language: node_js
node_js:
- '8'
git:
  depth: false
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "wslyvh-github"
    token:
      secure: ${SONAR_TOKEN}
before_install:
- npm update
- cd client
install:
- npm install
- npm install codecov -g
script:
- npm run lint
- npm run test
after_success:
  - codecov
  - sonar-scanner