sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "wslyvh-github"
before_install:
- npm update
- cd client
install:
- npm install
- npm install codecov -g
script:
- npm run lint
- npm run test
after_success:
  - codecov
  - sonar-scanner